preload = /home/arjun/.config/backgrounds/evening/sunrise-sky-stars-clouds-forest-scenery-digital-art-hd-wallpaper-uhdpaper.com-281@5@d.jpg
wallpaper = ,/home/arjun/.config/backgrounds/evening/sunrise-sky-stars-clouds-forest-scenery-digital-art-hd-wallpaper-uhdpaper.com-281@5@d.jpg
